---
name: Lint Code Base
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_RUBY: false
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundler
        run: |
          gem install bundler
          echo 'gem: --no-document' >> ~/.gemrc
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Lint Ruby
        run: |
          bundle exec standardrb